### ISSUE TITLE
How to run ToothGroupNetwork

### ISSUE THREAD

**Issue by hx171220** [limhoyeon/ToothGroupNetwork#10]
Hello:

   I'm using the main branch an follow the procedure:

1.  use challenger dataset to process,
2.  use processing data to train
3.  use the training results to verify 
  However, the following error occurred
![微信图片_20230710100957](https://github.com/limhoyeon/ToothGroupNetwork/assets/110795790/e2fef969-6999-4146-9b9e-3f24fdbd89e7)
My running environment：
- The graphics card is RTX 3090
- Python 3.7.0
- torch: 1.13.1+cu117, cuda 11.7,cudnn 8500
- Ubuntu 20.4
Now I don't know where the problem is, Can you help me?

**Comment by limhoyeon** [comment]
please tell me what options you used for train and inference!

**Comment by hx171220** [comment]
This is my options:

- **train**: python start_train.py --model_name "tgnet_fps" --config_path "train_configs/tgnet_fps.py" --experiment_name "tgnet" --input_data_dir_path "../processDir" --train_data_split_txt_path "../split/base_name_train_fold.txt" --val_data_split_txt_path "../split/base_name_val_fold.txt"
- **verify**: python start_inference.py --input_dir_path /home/ecs-user/ToothGroupNetwork-main/modelDir --split_txt_path /home/ecs-user/ToothGroupNetwork-main/split/base_name_test_fold.txt --save_path /home/ecs-user/ToothGroupNetwork-main/result --model_name tgnet --checkpoint_path /home/ecs-user/ToothGroupNetwork-main/ckpts/tgnet_75 --checkpoint_path_bdl /home/ecs-user/ToothGroupNetwork-main/ckpts/tgnet_val

tgnet_75.h5 and tgnet_val.h5 are generated training sets

I modified the following configuration：
![微信截图_20230711092041](https://github.com/limhoyeon/ToothGroupNetwork/assets/110795790/847ab446-73da-4295-bd69-2ca8a1cde91a)

![微信截图_20230711092511](https://github.com/limhoyeon/ToothGroupNetwork/assets/110795790/53aa47cd-d263-4631-9654-34b2aacadce1)
Is there anything else that needs to be changed?

**Comment by JeffreyWardman** [comment]
@limhoyeon has not provided up to date models and needs to reupload them

**Comment by limhoyeon** [comment]
Make sure to train both the tgnet_fps model and the tgnet_bdl model! Our tgnet needs two checkpoints(tgnet_bdl, tgnet_fps) to make inferences. For more details, see the train section of the readme. Let me know if you have any further questions.

**Comment by hx171220** [comment]
@limhoyeon Thank you. I'll check it first and get back to you if I have any questions
