### ISSUE TITLE
How to train other data

### ISSUE THREAD

**Issue by hx171220** [limhoyeon/ToothGroupNetwork#13]
Thank you for your help, The model can now be split normally
![微信图片_20230724093341](https://github.com/limhoyeon/ToothGroupNetwork/assets/110795790/61036b61-95fb-4e87-bd6d-969ec10a53a0)
However, the segmentation of our own model using the training set after training is not very good, we want to train the dental model that meets our requirement，But it need some split_json data, How to generate a split json file，Plase help me.

**Comment by hx171220** [comment]
I noticed there was such a file
![微信图片_20230724103038](https://github.com/limhoyeon/ToothGroupNetwork/assets/110795790/1edaac82-93be-4a37-8a3a-bdc8394048a0)
But found this missing
![微信图片_20230724103205](https://github.com/limhoyeon/ToothGroupNetwork/assets/110795790/7185dc50-6601-4fd1-b90a-c727598d992a)

**Comment by hx171220** [comment]
@limhoyeon Please help me answer this question

**Comment by limhoyeon** [comment]
I modified the split_txt_maker.py. please check that code. Thanks.
