### ISSUE TITLE
ground-truth_labels_instances

### ISSUE THREAD

**Issue by jhpdavid** [limhoyeon/ToothGroupNetwork#17]
Hello

First of all, thank you for doing good research.

The json file in the ground-truth_labels_instances folder has 'labels' and 'instances', what does each mean?
When I open the json file, I think labels are tooth numbers, but I don't know the meaning of instances. (In the paper, instances are tooth numbers. Which one is right?)

I would appreciate it if you could tell me the meaning of 'labels' and 'instances' in the json file.

thank you

**Comment by limhoyeon** [comment]
Im sorry for late reply.

"labels" are fdi id of each point, and instances just are the tooth instance number that each point belongs to

**Comment by SimonZhao777** [comment]
hi thanks for the good work, I still don't understand what's the meaning of 'tooth instance number', it seems to me that tooth instance number did not bring any extra-information other than 'labels'(which are fdi id of each point) if it's just a random number to differenciate different tooths, I mean labels can already help me to do that, please correct me if I miss-understand it, thank you again for the great work!

**Comment by supgy** [comment]
> hi thanks for the good work, I still don't understand what's the meaning of 'tooth instance number', it seems to me that tooth instance number did not bring any extra-information other than 'labels'(which are fdi id of each point) if it's just a random number to differenciate different tooths, I mean labels can already help me to do that, please correct me if I miss-understand it, thank you again for the great work!

I have the same problem, and i notice that the same labels number corresponding to different instance number in each json.

**Comment by SimonZhao777** [comment]
> > hi thanks for the good work, I still don't understand what's the meaning of 'tooth instance number', it seems to me that tooth instance number did not bring any extra-information other than 'labels'(which are fdi id of each point) if it's just a random number to differenciate different tooths, I mean labels can already help me to do that, please correct me if I miss-understand it, thank you again for the great work!
> 
> I have the same problem, and i notice that the same labels number corresponding to different instance number in each json.

I managed to figure it out, the instance number is an indicator for the type of teeth, such as canine, incisor, molar etc. noticed that FDI index provided an more detailed information about each teeth, so instance number could easily be inferred out from FDI index.

**Comment by madhavkrishnan94** [comment]
I have a related question. If I already have an array of all labels for every vertex, how do I generate an array of labels and instances (basically the whole json file)?
