### ISSUE TITLE
How to train ToothGroupNetwork

### ISSUE THREAD

**Issue by liufububai** [limhoyeon/ToothGroupNetwork#3]
Hello,

"if you want to train our model, please contact me.
The training code will be updated and released during May 2023."

How to train this model and I don't find your email.

Please let me know.

Thanks!

**Comment by limhoyeon** [comment]
Hello.

I apologize for the delay in making it public, as I have been occupied with
graduation preparations. I plan to release it within the next two weeks.

Best regards
Lim

**Comment by liufububai** [comment]
I meet error on this cd external_libs/pointops && python setup.py install like 
"File "/.../python3.8/site-packages/torch/utils/cpp_extension.py", line 1555, In_run_ninja_build raise RuntimeError(message) from e 
RuntimeError: Error compiling objects for extension"

What's your python version?

**Comment by limhoyeon** [comment]
Maybe this issue is related to cuda compiler(nvcc) and compiler.
Are nvcc and compiler(maybe gcc in ubuntu) installed in your environment?
My python version is 3.7.

**Comment by liufububai** [comment]
I rent a cloud GPU server and CUDA driver is 12.0. Maybe you are right that it is the cuda version and environment setttings problems.
I will try to set them as you recommend.
Thanks!

**Comment by liufububai** [comment]
We solve the problem by reinstall CUDA driver.  We can generate .json, but we don't quite understand the meaning of label "instances".  

We read this link: https://github.com/abenhamadou/3DTeethSeg22_challenge/blob/main/evaluation/export_labeled_3Dscan.py

But, we don't fully understand this code and visualize wrong results. We think the color is assign on vertices. How to recover the color to mesh?
![incorrect](https://github.com/limhoyeon/ToothGroupNetwork/assets/11657709/d4ffebfc-6825-46e4-ab00-fa79514cdda3)

**Comment by limhoyeon** [comment]
Yes, the challenge data assigns colors to the vertices, and the color of
the each face is determined by the vertex colors of each face.
Do you have miccai challenge dataset? Maybe you can test the visualization
code with miccai challenge dataset.

**Comment by liufububai** [comment]
Sorry, I don't have miccai challenge dataset. 
So far, I don't figure out how to apply miccai challenge dataset, which looks closing the application of dataset.
We find lower jaws look correct, but upper jaws look wrong. Do you think it is caused by jaw data format?
And the key of "instances" means the id of teeth for a vertex or the number of teeth in  the 3D scan.
It is hard to understand the meaning.

**Comment by limhoyeon** [comment]
Plz check data description! maybe the upper jaw have to be rotated, so that the upper jaw and the lower jaw have same axis.

And the key of "instances" means the id of teeth for a vertex.
If the instance number of vertex is "34", this vertex belongs to 34(in fdi tooth numbering system).
the order of the "instaces" array is the same as obj file vertex order.

**Comment by liufububai** [comment]
Thanks. We get results after we rotate upper jaws to the same poses of lower jaws.
Another issues is that we find the teeth are not semented completely, see our snapshot:
![ToothGroupNetwork_results1](https://github.com/limhoyeon/ToothGroupNetwork/assets/11657709/b2285923-f010-418e-b4e0-61522ae6ee56)
The areas near gingiva are incorrect.  Is this issues caused by sampling?

**Comment by limhoyeon** [comment]
can you give me the sampled point cloud visualization results?

**Comment by limhoyeon** [comment]
plz refer to https://github.com/limhoyeon/ToothGroupNetwork/issues/4

**Comment by gxu12** [comment]
@liufububai is it possible for you to teach me how to create json file? or can you leave your contact emails? pretty appreciate
