### ISSUE TITLE
bad result when inputting mirrored data

### ISSUE THREAD

**Issue by whywhyf** [limhoyeon/ToothGroupNetwork#30]
## 1 what happened
- when i input a normal data, the model gives out a perfect result. however when i mirror(Left-right) the data then input it, the model gives out a bad result using a abnormal mount of time
## 2 problem
- i believe that, as teeth, the mirrored data should have the similar result as normal data. Becuase teeth should have the property of symmetry
- so what's the sitution？Did i do something wrong?
- how should i solve it? 
- Thank you for your help!
## 3 results of normal data and mirrored data
|          | normal data                                                         | mirrored data                                                     |
| -------- | ------------------------------------------------------------ | ------------------------------------------------------------ |
| Runtime duration     | 30s                                                          | 210s                                                         |
| segment result | ![image-20240328202646030](https://github.com/limhoyeon/ToothGroupNetwork/assets/116568236/9d5e64f3-a139-48a1-887a-0c04b393ac49) | ![image-20240328185736523-1711623553771-2](https://github.com/limhoyeon/ToothGroupNetwork/assets/116568236/df365601-49eb-41de-b492-bf61c5d6145c)
| segment result |![image-20240328202658408](https://github.com/limhoyeon/ToothGroupNetwork/assets/116568236/acb793b2-0f67-49cd-a2a3-f7a6c916cd25)| ![image-20240328185935952](https://github.com/limhoyeon/ToothGroupNetwork/assets/116568236/0a12d06a-ce70-4980-a739-cc34ed3a2592)|
## 4 detail
- The input data follows the principle of coordinate alignment
- the input data is not from the dataset of this model. i will try this on dataset of this model later

**Comment by limhoyeon** [comment]
Thank you for your attention for my research.
Could I ask you how you mirrored the data? Did you just filpped the coordinates value of each point?

**Comment by whywhyf** [comment]
Thank you for your attention and reply.
yes, I just simply multiply the x-coordinate values of the points by -1.
- normal:[x,y,z]
- mirrored:[-x,y,z]
```python
T = [[-1, 0, 0, 0],  
     [0, 1, 0, 0],  
     [0, 0, 1, 0],  
     [0, 0, 0, 1]]  
mesh.transform(T)  
```
- I noticed that the mirrored data has opposite normal vectors. But the Tgnet just needs vertices and faces right?
- I have manully ignored normal vectors when inputting data to Tgnet. (Because the mirrored obj file has normal vectors.)

**Comment by whywhyf** [comment]
I have tryed this on data(id:00OMSZGW) of your dataset. The segment result is still not ideal.
However, I found that when i visualize the data by open3d, it seems that o3d knows the normal vectors of data, though the obj file has no nromal vectors information (vn). 
And it shows that when i mirrored the data, the normal vectors were also flipped.(maybe this is the reason of bad result?)
I was confused because I thought that we can not get normal vectors since the obj had no vn informations

can this be a reason of bad seg result?
how can open3d get normal vectors since the obj had no vn informations?

## visualized seg result of mirrored 00OMSZGW
we can see that open3d knows the normal vectors
normal data, open3d can get the normal vectors now:
![image](https://github.com/limhoyeon/ToothGroupNetwork/assets/116568236/af453758-c828-4707-8038-29b92d77b30f)
mirrored data, open3d shows the flipped normal vectors:
![image](https://github.com/limhoyeon/ToothGroupNetwork/assets/116568236/d5daa75c-0c7e-4ae2-99e9-b7262161b08a)
seg result of mirrored data:
![image](https://github.com/limhoyeon/ToothGroupNetwork/assets/116568236/f1579140-5d82-4b57-ae39-c7b7a1b31fe3)

**Comment by whywhyf** [comment]
I figured it out. 
In the obj file, the order of point index in 'f' line can represent the direction of normal vectors.
Vertices are stored in the counterclockwise direction by default, so there is no need to explicitly declare the normal vector direction.
So the bad result of mirrored data is cause by flipped normal vectors(auto happened when simply filpping the x-coordinates value of each point), which are part of model's input.

If you want to test mirrored data, don't forget to adjust the index orders in 'f' line, making sure the normal vectors is still facing outwards.

**Comment by supgy** [comment]
> ## 1 what happened
> * when i input a normal data, the model gives out a perfect result. however when i mirror(Left-right) the data then input it, the model gives out a bad result using a abnormal mount of time
> 
> ## 2 problem
> * i believe that, as teeth, the mirrored data should have the similar result as normal data. Becuase teeth should have the property of symmetry
> * so what's the sitution？Did i do something wrong?
> * how should i solve it?
> * Thank you for your help!
> 
> ## 3 results of normal data and mirrored data
> normal data	mirrored data
> Runtime duration	30s	210s
> segment result	![image-20240328202646030](https://private-user-images.githubusercontent.com/116568236/318400400-9d5e64f3-a139-48a1-887a-0c04b393ac49.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc2Njk3MzAsIm5iZiI6MTcxNzY2OTQzMCwicGF0aCI6Ii8xMTY1NjgyMzYvMzE4NDAwNDAwLTlkNWU2NGYzLWExMzktNDhhMS04ODdhLTBjMDRiMzkzYWM0OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwNlQxMDIzNTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01YTMyN2EyNjFlNzlmMTQ1ZmI5OTNmNTdkOTZiMGM3ZWQ1MDE3MTYwMzE3ZmI0ODY4ZGRkODM0ZDc1ZmFlNjExJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Wk7-b5FFZreGdfV8GHF5QDHkCCZ_QxgP2JIcWNvUagU)	![image-20240328185736523-1711623553771-2](https://private-user-images.githubusercontent.com/116568236/318400666-df365601-49eb-41de-b492-bf61c5d6145c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc2Njk3MzAsIm5iZiI6MTcxNzY2OTQzMCwicGF0aCI6Ii8xMTY1NjgyMzYvMzE4NDAwNjY2LWRmMzY1NjAxLTQ5ZWItNDFkZS1iNDkyLWJmNjFjNWQ2MTQ1Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwNlQxMDIzNTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xMDNiNTZmMDA5ZmUwN2UwNDUwZDg2NTQwMDQ1N2RhZjMyYzg4MzVkZmEyNjZiMDE4NDY2OWIxODVlMTEyN2NlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Knqhs8U0IQr5gidK4xuOrpkbIomd6xoLMLRkLkilHOU)
> segment result	![image-20240328202658408](https://private-user-images.githubusercontent.com/116568236/318400970-acb793b2-0f67-49cd-a2a3-f7a6c916cd25.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc2Njk3MzAsIm5iZiI6MTcxNzY2OTQzMCwicGF0aCI6Ii8xMTY1NjgyMzYvMzE4NDAwOTcwLWFjYjc5M2IyLTBmNjctNDljZC1hMmEzLWY3YTZjOTE2Y2QyNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwNlQxMDIzNTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hM2Q4Yzc2ZDEwYTYwYmY5OGQxYjRhMjNjZmJhZTU4MjUxYjM0ODYxMGUxMjBjOTdhMjI0ZmRmMWUyYjMxNzUxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.DtWZPdR81f0krQlgnZ0I2JaZ60YYPwO4oTYHr4ulSRA)	![image-20240328185935952](https://private-user-images.githubusercontent.com/116568236/318401013-0a12d06a-ce70-4980-a739-cc34ed3a2592.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc2Njk3MzAsIm5iZiI6MTcxNzY2OTQzMCwicGF0aCI6Ii8xMTY1NjgyMzYvMzE4NDAxMDEzLTBhMTJkMDZhLWNlNzAtNDk4MC1hNzM5LWNjMzRlZDNhMjU5Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwNlQxMDIzNTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02YTkyZGExZjBkYjhjY2ExMGUzNWNhZTI4MTgyZjhkY2VhZjFiZmZmODY1NDZjMmJiZTFkNTNiZDNkN2Q2OGExJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.248-Qe85FvXb1unYB1DNKRv4OOOxSn7flchc3F7ve8A)
> ## 4 detail
> * The input data follows the principle of coordinate alignment
> * the input data is not from the dataset of this model. i will try this on dataset of this model later

Hello, I have a question and would like to ask for advice.  Are you testing directly using pretrained models on your own data?Did you modify any parameters during testing?
