### ISSUE TITLE
about first_ins_cent_model Problem

### ISSUE THREAD

**Issue by 0ZzYy0** [limhoyeon/ToothGroupNetwork#4]
Hello, I used the challenge dataset and your shared model for prediction. However, there seems to be an issue with the ’self.first_ins_cent_model‘ method in the ’grouping_network_module.py‘ file, which results in all 0 values for whole_cls_1.
![Snipaste_2023-06-14_11-11-46](https://github.com/limhoyeon/ToothGroupNetwork/assets/35437647/c76b92ec-c775-446f-afa9-356e40ccb60a)

**Comment by limhoyeon** [comment]
Can you give me the visualize result of the sampled points(maybe after farthest point sampling in my inference pipeline code)?

**Comment by 0ZzYy0** [comment]
Thank you for your response,The first image is vertices and the second image is sampled_feats.

![Snipaste_2023-06-14_12-24-32](https://github.com/limhoyeon/ToothGroupNetwork/assets/35437647/a32f49ce-a415-42e0-a7b8-bb59057f215a)

![Snipaste_2023-06-14_12-24-49](https://github.com/limhoyeon/ToothGroupNetwork/assets/35437647/5fc2b05a-cda0-4aa2-9960-6101cc2d6bc1)


![Snipaste_2023-06-14_12-26-58](https://github.com/limhoyeon/ToothGroupNetwork/assets/35437647/ac8418a9-1ef0-4b02-b2f4-a71fd9672145)

**Comment by 0ZzYy0** [comment]
I changed 'new_fps' to 'fps' in 'resample_pcd', and now it is working fine.

**Comment by limhoyeon** [comment]
can you tell me what our graphic cards and cuda version?

**Comment by 0ZzYy0** [comment]
The graphics card is RTX 3090

![cuda](https://github.com/limhoyeon/ToothGroupNetwork/assets/35437647/66391669-07ac-4d1e-9a5f-a6e86eedfdeb)


![nvidia](https://github.com/limhoyeon/ToothGroupNetwork/assets/35437647/bb4b0d43-ba21-4a3a-a641-80db526723a4)

**Comment by koushiyu** [comment]
牛逼

**Comment by limhoyeon** [comment]
As I said previously, maybe it is related to the cuda function in the point
transformer model(original code ->
https://github.com/LiyaoTang/contrastBoundary].
I think that there are some problems when executing the cuda function in
Rtx 30XX versions.

I apologize for not being able to assist you immediately, as it might take
some time to identify the issues with the CUDA function and modify the code.

**Comment by 0ZzYy0** [comment]
Thank you very much for your help. I will continue to try different methods to solve this problem.

**Comment by limhoyeon** [comment]
If you download the original pointops library, you might solve your problem. plz refer to https://github.com/limhoyeon/ToothGroupNetwork/issues/7

**Comment by coordxyz** [comment]
Hi, @0ZzYy0 , Could please tell me how to visualize the sampled boundary points with instance labels and the centroids? Thx~
