### ISSUE TITLE
Training checkpoints

### ISSUE THREAD

**Issue by msafdari1234** [limhoyeon/ToothGroupNetwork#5]
Thanks for posting your code. The folder you are sharing the training checkpoint, you have posted 'ckpts(new).egg' file. I was wondering if this is a typo or if not, how I can install it. From what I know, .egg python package files are deprecated. Thanks!

**Comment by limhoyeon** [comment]
The .egg file format is simply a compressed file format. You can find how to extract the contents of an .egg file by searching web.

Thank you.

**Comment by msafdari1234** [comment]
Thanks. Got it extracted. Seems to be same checkpoints as those in "ckpts(challenge).zip"
